#!/usr/bin/env bash

apt-get update -y

dpkg -l | grep -qw nginx || apt-get install -y nginx

systemctl start nginx

systemctl enable nginx

ufw allow 80/tcp || true

sed -i 's/^# server {/server {/' /etc/nginx/sites-available/default
sed -i 's/^#	listen 80 default_server;/	listen 80 default_server;/' /etc/nginx/sites-available/default
sed -i 's/^#	listen \[::\]:80 default_server;/	listen [::]:80 default_server;/' /etc/nginx/sites-available/default

systemctl restart nginx
